// Juan Pedro Puig - 281088
// Nicolás Valsecchi - 192765

package interfaz;

import javax.swing.JOptionPane;
import dominio.Sistema;
import dominio.Empleado;
import dominio.Persona;

public class VentanaRegistroEmpleado extends javax.swing.JFrame {
    //Atributo
    private Sistema modelo;
    
    //Constructor
    public VentanaRegistroEmpleado(Sistema unSistema) {
        modelo = unSistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTituloRegistroEmpleado = new javax.swing.JLabel();
        jLabelCi = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelAnoIngreso = new javax.swing.JLabel();
        jTextFieldCi = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldAnoIngreso = new javax.swing.JTextField();
        jButtonAgregarEmpleado = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Auto-almacenamiento");

        jLabelTituloRegistroEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTituloRegistroEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloRegistroEmpleado.setText("Registro de empleado");

        jLabelCi.setText("Cédula de identidad (sin puntos, ni guiones):");

        jLabelNombre.setText("Nombre y apellido:");

        jLabelTelefono.setText("Teléfono de contacto:");

        jLabelDireccion.setText("Dirección de domicilio:");

        jLabelAnoIngreso.setText("Año de ingreso a la empresa:");

        jTextFieldCi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCiActionPerformed(evt);
            }
        });

        jButtonAgregarEmpleado.setText("Agregar empleado");
        jButtonAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarEmpleadoActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDireccion)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldDireccion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNombre)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCi)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCi, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTelefono)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelAnoIngreso)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldAnoIngreso))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jButtonAgregarEmpleado)
                        .addGap(94, 94, 94)
                        .addComponent(jButtonSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabelTituloRegistroEmpleado)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabelTituloRegistroEmpleado)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCi)
                    .addComponent(jTextFieldCi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefono)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDireccion)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAnoIngreso)
                    .addComponent(jTextFieldAnoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregarEmpleado)
                    .addComponent(jButtonSalir))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCiActionPerformed

    }//GEN-LAST:event_jTextFieldCiActionPerformed

    //Boton para enviar empleado
    private void jButtonAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarEmpleadoActionPerformed
        int ci = 0;
        int telefono = 0;
        int anoIngreso = 0;
        String nombre = jTextFieldNombre.getText();
        String direccion = jTextFieldDireccion.getText();
        
        if (jTextFieldCi.getText().equals("") || nombre.equals("") || jTextFieldTelefono.getText().equals("") ||
                direccion.equals("") || jTextFieldAnoIngreso.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos los campos deben estar completos", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            boolean ok = true;
            
            try {
                ci = Integer.parseInt(jTextFieldCi.getText());
                telefono = Integer.parseInt(jTextFieldTelefono.getText());
                anoIngreso = Integer.parseInt(jTextFieldAnoIngreso.getText());
                if (ci < 1 || telefono < 1 || anoIngreso < 1) {
                    JOptionPane.showMessageDialog(this, "Los números ingresados deben ser positivos.", "Error", JOptionPane.WARNING_MESSAGE);
                    ok = false;
                } else {
                    if (anoIngreso > 2022) {
                        JOptionPane.showMessageDialog(this, "El año de ingreso no puede ser mayor al actual.", "Error", JOptionPane.WARNING_MESSAGE);
                        ok = false;
                    }
                }   
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Los campos de cédula de identidad, teléfono y año de ingreso solo permiten números.", "Error", JOptionPane.WARNING_MESSAGE);
                ok = false;
            }
            
            if (ok) {
                Empleado e = new Empleado(ci, nombre, telefono, direccion, anoIngreso);
                if (!modelo.existe(modelo.getListaClientes(), e) && !modelo.existe(modelo.getListaEmpleados(), (Persona) e)) {
                    modelo.agregarEmpleado(e);
                    JOptionPane.showMessageDialog(this, "El empleado se ha ingresado con éxito.", "Empleado ingresado", JOptionPane.INFORMATION_MESSAGE);
                    jTextFieldCi.setText("");
                    jTextFieldNombre.setText("");
                    jTextFieldTelefono.setText("");
                    jTextFieldDireccion.setText("");
                    jTextFieldAnoIngreso.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "La persona que está intentando ingresar ya se encuentra en el sistema.", "Persona existente", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButtonAgregarEmpleadoActionPerformed
    //Boton para salir
    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarEmpleado;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelAnoIngreso;
    private javax.swing.JLabel jLabelCi;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTituloRegistroEmpleado;
    private javax.swing.JTextField jTextFieldAnoIngreso;
    private javax.swing.JTextField jTextFieldCi;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
