// Juan Pedro Puig - 281088
// Nicolás Valsecchi - 192765

package interfaz;

import dominio.Cliente;
import dominio.Contrato;
import dominio.Deposito;
import dominio.Empleado;
import dominio.Sistema;
import java.util.*;
import javax.swing.JOptionPane;

public class VentanaRegistroContrato extends javax.swing.JFrame implements Observer {
    //Atributos
    private Sistema modelo;
    
    //Constructor
    public VentanaRegistroContrato(Sistema unSistema) {
        modelo = unSistema;
        modelo.addObserver(this);
        initComponents();
        jListEmpleados.setListData(modelo.getListaEmpleados().toArray());
        jListClientes.setListData(modelo.getListaClientes().toArray());
        jListDepositos.setListData(new String[0]);
        jRadioButtonIndiferenteEstantes.setSelected(true);
        jRadioButtonIndiferenteRefrigerado.setSelected(true); 
        
        //https://coderanch.com/t/641342/java/Changing-color-JList-item
        jListDepositos.setCellRenderer(new MyCellRenderer());
        
        update(null, null);
    }
    
    public void update(Observable o, Object obj) {
        jListEmpleados.setListData(modelo.getListaEmpleados().toArray());
        jListClientes.setListData(modelo.getListaClientes().toArray());
        jListDepositos.setListData(new String[0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupConEstantes = new javax.swing.ButtonGroup();
        buttonGroupRefrigerado = new javax.swing.ButtonGroup();
        jLabelTituloContrato = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEmpleados = new javax.swing.JList();
        jLabelEmpleados = new javax.swing.JLabel();
        jLabelClientes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListClientes = new javax.swing.JList();
        jLabelDepositos = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListDepositos = new javax.swing.JList();
        jLabelDetalle = new javax.swing.JLabel();
        jTextFieldDetalle = new javax.swing.JTextField();
        jButtonAgregarContrato = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonConEstantes = new javax.swing.JRadioButton();
        jRadioButtonSinEstantes = new javax.swing.JRadioButton();
        jRadioButtonIndiferenteEstantes = new javax.swing.JRadioButton();
        jRadioButtonEsRefrigerado = new javax.swing.JRadioButton();
        jRadioButtonNoEsRefrigerado = new javax.swing.JRadioButton();
        jRadioButtonIndiferenteRefrigerado = new javax.swing.JRadioButton();
        jButtonMostrarDepositos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTamanoMinimo = new javax.swing.JTextField();
        jTextFielTamanoMaximo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Auto-almacenamiento");

        jLabelTituloContrato.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTituloContrato.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloContrato.setText("Registro de contrato");

        jListEmpleados.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListEmpleados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jListEmpleados);

        jLabelEmpleados.setText("Empleados:");

        jLabelClientes.setText("Clientes:");

        jListClientes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListClientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jListClientes);

        jLabelDepositos.setText("Depósitos:");

        jListDepositos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListDepositos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jListDepositos);

        jLabelDetalle.setText("Detalle:");

        jTextFieldDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDetalleActionPerformed(evt);
            }
        });

        jButtonAgregarContrato.setText("Agregar contrato");
        jButtonAgregarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarContratoActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jLabel1.setText("Con estantes:");

        jLabel2.setText("Refrigerado:");

        buttonGroupConEstantes.add(jRadioButtonConEstantes);
        jRadioButtonConEstantes.setText("Si");

        buttonGroupConEstantes.add(jRadioButtonSinEstantes);
        jRadioButtonSinEstantes.setText("No");

        buttonGroupConEstantes.add(jRadioButtonIndiferenteEstantes);
        jRadioButtonIndiferenteEstantes.setText("Indiferente");

        buttonGroupRefrigerado.add(jRadioButtonEsRefrigerado);
        jRadioButtonEsRefrigerado.setText("Si");

        buttonGroupRefrigerado.add(jRadioButtonNoEsRefrigerado);
        jRadioButtonNoEsRefrigerado.setText("No");

        buttonGroupRefrigerado.add(jRadioButtonIndiferenteRefrigerado);
        jRadioButtonIndiferenteRefrigerado.setText("Indiferente");

        jButtonMostrarDepositos.setText("Mostrar depósitos disponibles");
        jButtonMostrarDepositos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarDepositosActionPerformed(evt);
            }
        });

        jLabel3.setText("Tamaño:");

        jLabel4.setText("Mín:");

        jLabel5.setText("Máx:");

        jTextFielTamanoMaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielTamanoMaximoActionPerformed(evt);
            }
        });

        jLabel6.setText("m2.");

        jLabel7.setText("m2.");

        jLabel8.setText("Características del depósito deseado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDetalle)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDetalle)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jButtonAgregarContrato)
                        .addGap(204, 204, 204)
                        .addComponent(jButtonSalir)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEmpleados)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelClientes)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonSinEstantes)
                                    .addComponent(jRadioButtonConEstantes)
                                    .addComponent(jLabel1)
                                    .addComponent(jRadioButtonIndiferenteEstantes))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonNoEsRefrigerado)
                                    .addComponent(jRadioButtonIndiferenteRefrigerado)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButtonEsRefrigerado)
                                            .addComponent(jLabel2))
                                        .addGap(15, 15, 15))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(4, 4, 4)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFielTamanoMaximo)
                                    .addComponent(jTextFieldTamanoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jButtonMostrarDepositos, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDepositos)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                .addGap(32, 32, 32))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addComponent(jLabelTituloContrato)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabelTituloContrato)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonConEstantes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonSinEstantes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonIndiferenteEstantes))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonEsRefrigerado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonNoEsRefrigerado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonIndiferenteRefrigerado)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTamanoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFielTamanoMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonMostrarDepositos))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelEmpleados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelDepositos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3)))
                .addGap(29, 29, 29)
                .addComponent(jLabelDetalle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregarContrato)
                    .addComponent(jButtonSalir))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDetalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDetalleActionPerformed
    
    //Boton para agregar contrato
    private void jButtonAgregarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarContratoActionPerformed
        Empleado emp = (Empleado) jListEmpleados.getSelectedValue();
        Cliente cli = (Cliente) jListClientes.getSelectedValue();
        Deposito dep = (Deposito) jListDepositos.getSelectedValue();
        String detalle = jTextFieldDetalle.getText();
        
        
        if (detalle.equals("")) {
            detalle = "Sin detalle";
        }
        
        if (emp == null || cli == null || dep == null) {
            JOptionPane.showMessageDialog(this, "Se debe seleccionar un valor de cada lista.", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            Contrato c = new Contrato(cli, emp, dep, detalle);
            dep.setContratado(true);
            modelo.agregarContrato(c);
            JOptionPane.showMessageDialog(this, "El contrato se ha ingresado con éxito.", "Contrato ingresado", JOptionPane.INFORMATION_MESSAGE);
            //Limpiar valores
            jTextFieldTamanoMinimo.setText("");
            jTextFielTamanoMaximo.setText("");
            jRadioButtonIndiferenteEstantes.setSelected(true);
            jRadioButtonIndiferenteRefrigerado.setSelected(true);
            jListDepositos.setListData(new String[0]);
            jListClientes.clearSelection();
            jListEmpleados.clearSelection();
            jTextFieldDetalle.setText("");
        }
    }//GEN-LAST:event_jButtonAgregarContratoActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFielTamanoMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielTamanoMaximoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielTamanoMaximoActionPerformed
    //Boton para mostrar depositos filtrados
    private void jButtonMostrarDepositosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarDepositosActionPerformed
        int tamanoMin = 0;
        int tamanoMax = 0;
        int estantes = 0;
        int refrigerado = 0;
        boolean okTamano = true;
        
        if (jRadioButtonConEstantes.isSelected()) {
            estantes = 1;
        } else {
            if (jRadioButtonSinEstantes.isSelected()) {
                estantes = -1;
            }
        }
        
        if (jRadioButtonEsRefrigerado.isSelected()) {
            refrigerado = 1;
        } else {
            if (jRadioButtonNoEsRefrigerado.isSelected()) {
                refrigerado = -1;
            }
        }
        
        try {
            tamanoMin = Integer.parseInt(jTextFieldTamanoMinimo.getText());
            tamanoMax = Integer.parseInt(jTextFielTamanoMaximo.getText());
            
            if (tamanoMin < 0 || tamanoMin > tamanoMax){
            JOptionPane.showMessageDialog(this, "Solo se admiten números positivos.\nEl tamaño mínimo no puede ser mayor al tamaño máximo.", "Error", JOptionPane.WARNING_MESSAGE);
            okTamano = false;
        }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Los campos solo admiten números. No pueden estar vacíos.", "Error", JOptionPane.WARNING_MESSAGE);
            okTamano = false;
        }

        if (okTamano) {            
            jListDepositos.setListData(modelo.obtenerDepositosDisponibles(estantes, refrigerado, tamanoMin, tamanoMax).toArray());
        }
    }//GEN-LAST:event_jButtonMostrarDepositosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupConEstantes;
    private javax.swing.ButtonGroup buttonGroupRefrigerado;
    private javax.swing.JButton jButtonAgregarContrato;
    private javax.swing.JButton jButtonMostrarDepositos;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelDepositos;
    private javax.swing.JLabel jLabelDetalle;
    private javax.swing.JLabel jLabelEmpleados;
    private javax.swing.JLabel jLabelTituloContrato;
    private javax.swing.JList jListClientes;
    private javax.swing.JList jListDepositos;
    private javax.swing.JList jListEmpleados;
    private javax.swing.JRadioButton jRadioButtonConEstantes;
    private javax.swing.JRadioButton jRadioButtonEsRefrigerado;
    private javax.swing.JRadioButton jRadioButtonIndiferenteEstantes;
    private javax.swing.JRadioButton jRadioButtonIndiferenteRefrigerado;
    private javax.swing.JRadioButton jRadioButtonNoEsRefrigerado;
    private javax.swing.JRadioButton jRadioButtonSinEstantes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextFielTamanoMaximo;
    private javax.swing.JTextField jTextFieldDetalle;
    private javax.swing.JTextField jTextFieldTamanoMinimo;
    // End of variables declaration//GEN-END:variables
}
