// Juan Pedro Puig - 281088
// Nicolás Valsecchi - 192765

package interfaz;

import dominio.Sistema;
import dominio.Deposito;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import java.math.*;



public class VentanaMenu extends javax.swing.JFrame {
    //Atributo
    private Sistema modelo;
    
    //Constructor
    public VentanaMenu(Sistema unSistema) {
        modelo = unSistema;
        initComponents();
    }

    private class DepositoListener implements ActionListener {
        public void actionPerformed(ActionEvent e) {
        // este código se ejecutará al presionar el botón, obtengo cuál botón
            JButton cual = ((JButton) e.getSource());
            JFrame hola = new JFrame();
            hola.setVisible(true);
 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBarAutoAlmacenamiento = new javax.swing.JMenuBar();
        jMenuRegistros = new javax.swing.JMenu();
        jMenuItemRegistroDeposito = new javax.swing.JMenuItem();
        jMenuItemRegistroEmpleado = new javax.swing.JMenuItem();
        jMenuItemRegistroCliente = new javax.swing.JMenuItem();
        jMenuItemRegistroContrato = new javax.swing.JMenuItem();
        jMenuItemVisitaDepósito = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();
        jMenuItemConsultaContratos = new javax.swing.JMenuItem();
        jMenuItemConsultaDepositos = new javax.swing.JMenuItem();
        jMenuItemEstadisticaOcupacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Auto-almacenamiento");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Auto-almacenamiento");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 5)); // NOI18N
        jLabel2.setText("Hecho por Juan Pedro Puig, Nicolás Valsecchi en Montevideo, Uruguay");

        jMenuRegistros.setText("Registros");

        jMenuItemRegistroDeposito.setText("Registro de depósito");
        jMenuItemRegistroDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistroDepositoActionPerformed(evt);
            }
        });
        jMenuRegistros.add(jMenuItemRegistroDeposito);

        jMenuItemRegistroEmpleado.setText("Registro de empleado");
        jMenuItemRegistroEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistroEmpleadoActionPerformed(evt);
            }
        });
        jMenuRegistros.add(jMenuItemRegistroEmpleado);

        jMenuItemRegistroCliente.setText("Registro de cliente");
        jMenuItemRegistroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistroClienteActionPerformed(evt);
            }
        });
        jMenuRegistros.add(jMenuItemRegistroCliente);

        jMenuItemRegistroContrato.setText("Registro de contrato");
        jMenuItemRegistroContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistroContratoActionPerformed(evt);
            }
        });
        jMenuRegistros.add(jMenuItemRegistroContrato);

        jMenuItemVisitaDepósito.setText("Visita a depósito");
        jMenuItemVisitaDepósito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVisitaDepósitoActionPerformed(evt);
            }
        });
        jMenuRegistros.add(jMenuItemVisitaDepósito);

        jMenuBarAutoAlmacenamiento.add(jMenuRegistros);

        jMenuConsultas.setText("Consultas");

        jMenuItemConsultaContratos.setText("Consultas de contratos");
        jMenuItemConsultaContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaContratosActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuItemConsultaContratos);

        jMenuItemConsultaDepositos.setText("Consulta de depósitos");
        jMenuItemConsultaDepositos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaDepositosActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuItemConsultaDepositos);

        jMenuItemEstadisticaOcupacion.setText("Estadística de ocupación");
        jMenuItemEstadisticaOcupacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEstadisticaOcupacionActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuItemEstadisticaOcupacion);

        jMenuBarAutoAlmacenamiento.add(jMenuConsultas);

        setJMenuBar(jMenuBarAutoAlmacenamiento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Boton para entrar a ventana de registro de depositos
    private void jMenuItemRegistroDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistroDepositoActionPerformed
        VentanaRegistroDeposito ventana = new VentanaRegistroDeposito(modelo);
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItemRegistroDepositoActionPerformed

    //Boton para entrar a ventana de registro de empleados
    private void jMenuItemRegistroEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistroEmpleadoActionPerformed
        VentanaRegistroEmpleado ventana = new VentanaRegistroEmpleado(modelo);
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItemRegistroEmpleadoActionPerformed

    //Boton para entrar a ventana de registro de clientes
    private void jMenuItemRegistroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistroClienteActionPerformed
        VentanaRegistroCliente ventana = new VentanaRegistroCliente(modelo);
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItemRegistroClienteActionPerformed

    //Boton para entrar a ventana de registro de contratos
    private void jMenuItemRegistroContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistroContratoActionPerformed
        VentanaRegistroContrato ventana = new VentanaRegistroContrato(modelo);
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItemRegistroContratoActionPerformed

    //Boton para entrar a ventana de consulta de depositos
    private void jMenuItemConsultaContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaContratosActionPerformed
        VentanaConsultaContratos ventana = new VentanaConsultaContratos(modelo);
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultaContratosActionPerformed

    //Boton para entrar a ventana de registro de visita
    private void jMenuItemVisitaDepósitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVisitaDepósitoActionPerformed
        VentanaVisitaDeposito ventana = new VentanaVisitaDeposito(modelo);
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItemVisitaDepósitoActionPerformed

    //Boton para entrar a ventana de consulta de disponibilidad depositos
    private void jMenuItemConsultaDepositosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaDepositosActionPerformed
       VentanaConsultaDepositos ventana = new VentanaConsultaDepositos(modelo);
       ventana.setVisible(true);       
    }//GEN-LAST:event_jMenuItemConsultaDepositosActionPerformed

    //Boton para entrar a ventana con grafico ocupacion
    private void jMenuItemEstadisticaOcupacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEstadisticaOcupacionActionPerformed
        CreateChart CC = new CreateChart("Pie Chart", modelo);
        CC.pack();
        CC.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemEstadisticaOcupacionActionPerformed

    //Metodo que guarda el sistema al cerrar el programa
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        modelo.guardarSistema(modelo);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBarAutoAlmacenamiento;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenuItem jMenuItemConsultaContratos;
    private javax.swing.JMenuItem jMenuItemConsultaDepositos;
    private javax.swing.JMenuItem jMenuItemEstadisticaOcupacion;
    private javax.swing.JMenuItem jMenuItemRegistroCliente;
    private javax.swing.JMenuItem jMenuItemRegistroContrato;
    private javax.swing.JMenuItem jMenuItemRegistroDeposito;
    private javax.swing.JMenuItem jMenuItemRegistroEmpleado;
    private javax.swing.JMenuItem jMenuItemVisitaDepósito;
    private javax.swing.JMenu jMenuRegistros;
    // End of variables declaration//GEN-END:variables
}
