// Juan Pedro Puig - 281088
// Nicolás Valsecchi - 192765

package interfaz;

import dominio.Contrato;
import dominio.Deposito;
import dominio.Sistema;
import java.awt.event.*;
import java.awt.*;
import java.util.*;
import javax.swing.*;
import static javax.swing.JOptionPane.*;

public class VentanaConsultaDepositos extends javax.swing.JFrame implements Observer {
    //Atributos
    private Sistema modelo;
    
    //Constructor
    public VentanaConsultaDepositos(Sistema unSistema) {
        modelo = unSistema;
        modelo.addObserver(this);
        initComponents();
        
        update(null, null);
    }
    
    public void update(Observable o, Object arg) {
        jPanelDepositos.removeAll();
        ArrayList<Deposito> depositos = modelo.getListaDepositos();
        
        Collections.sort(depositos, new Comparator<Deposito>() {
            public int compare(Deposito d1, Deposito d2) {
                return d1.getIdDeposito() - d2.getIdDeposito();
            }
        });
        
        for (Deposito d : depositos) {
            JButton nuevo = new JButton(" ");
            nuevo.setMargin(new Insets(-5, -5, -5, -5));
            if (d.getContratado()) {
                nuevo.setBackground(Color.RED);
            } else {
                nuevo.setBackground(Color.GREEN);
            }
            nuevo.setForeground(Color.BLACK);
            nuevo.setText("Núm: " + d.getIdDeposito());
            nuevo.addActionListener(new DepositoListener());
            jPanelDepositos.add(nuevo);            
        }
      //se oculta y vuelve a mostrar el panel para que se refresque el cambio
        jPanelDepositos.setVisible(false);
        jPanelDepositos.setVisible(true);
    }
    
    private class DepositoListener implements ActionListener {
        public void actionPerformed(ActionEvent e) {
            // este código se ejecutará al presionar el botón, obtengo cuál botón
            JButton cual = ((JButton) e.getSource());
            int id = Integer.parseInt(cual.getText().substring(5));
            Deposito d = modelo.obtenerDepositoPorId(id);
            Contrato c = modelo.obtenerContratoPorDeposito(d);
            String msj = d.toString();
            if (d.getContratado()) {
                msj = msj + "\nContrato:" + c.getIdContrato() + "\nCliente: " + c.getCliente() + ".\nEmpleado: " + c.getEmpleado() + ".";
            }
            
            JOptionPane.showMessageDialog(jPanelDepositos, msj, cual.getText(), PLAIN_MESSAGE);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelDepositos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Auto-almacenamiento");
        getContentPane().setLayout(null);

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitulo.setText("Consulta de depósitos");
        getContentPane().add(jLabelTitulo);
        jLabelTitulo.setBounds(212, 30, 145, 20);

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir);
        jButtonSalir.setBounds(250, 330, 72, 22);

        jPanelDepositos.setLayout(new java.awt.GridLayout(0, 5));
        jScrollPane1.setViewportView(jPanelDepositos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 70, 530, 230);

        setBounds(0, 0, 606, 423);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelDepositos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
