// Juan Pedro Puig - 281088
// Nicolás Valsecchi - 192765

package interfaz;

import dominio.Cliente;
import dominio.Contrato;
import dominio.Deposito;
import dominio.Empleado;
import dominio.Sistema;
import javax.swing.JOptionPane;
import dominio.Sistema;
import dominio.ArchivoGrabacion;
import dominio.Visita;
import dominio.Empleado;
import static java.lang.String.valueOf;
import java.util.*;
import javax.swing.table.DefaultTableModel;

public class VentanaConsultaContratos extends javax.swing.JFrame implements Observer {
    //Atributos
    private DefaultTableModel modeloTabla;
    private Sistema modelo;
    //Constructor
    public VentanaConsultaContratos(Sistema unSistema) {
        modelo = unSistema;
        modelo.addObserver(this);
        initComponents();
        
        jListContratos.setListData(modelo.getListaContratos().toArray());
        modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("Dia");
        modeloTabla.addColumn("Mes");
        modeloTabla.addColumn("Empleado");
        jTableVisitasContrato.setModel(modeloTabla);
        
        update(null, null);
    }

    public void update(Observable o, Object obj) {
        jListContratos.setListData(modelo.getListaContratos().toArray());
        jTextAreaInfoContrato.setText("");
        jTableVisitasContrato.setModel(modeloTabla);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelTituloContrato = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaInfoContrato = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableVisitasContrato = new javax.swing.JTable();
        jButtonBajaContrato = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListContratos = new javax.swing.JList();
        jButtonMostrarDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Auto-almacenamiento");

        jLabel1.setText("Contratos:");

        jLabelTituloContrato.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTituloContrato.setText("Consulta de Contratos");

        jTextAreaInfoContrato.setColumns(20);
        jTextAreaInfoContrato.setRows(5);
        jScrollPane2.setViewportView(jTextAreaInfoContrato);

        jTableVisitasContrato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dia", "Mes", "Empleado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableVisitasContrato);
        if (jTableVisitasContrato.getColumnModel().getColumnCount() > 0) {
            jTableVisitasContrato.getColumnModel().getColumn(1).setResizable(false);
        }

        jButtonBajaContrato.setText("Dar de baja el contrato");
        jButtonBajaContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaContratoActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jLabel2.setText("Información disponible del contrato:");

        jLabel3.setText("Visitas a depósito del contrato:");

        jListContratos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListContratos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(jListContratos);

        jButtonMostrarDatos.setText("Mostrar datos del contrato");
        jButtonMostrarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonMostrarDatos)
                        .addGap(37, 37, 37)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButtonBajaContrato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalir)
                        .addGap(49, 49, 49))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTituloContrato)
                .addGap(234, 234, 234))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabelTituloContrato)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMostrarDatos)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBajaContrato)
                    .addComponent(jButtonSalir))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Boton dar contrato de baja
    private void jButtonBajaContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaContratoActionPerformed
        if(jListContratos.getSelectedIndex() != -1){
            Contrato c = (Contrato) jListContratos.getSelectedValue();
            
            ArchivoGrabacion arch = new ArchivoGrabacion(c.getCliente().toString() + " " + c.getIdContrato() + ".txt");
            for (Visita v : modelo.ordenarVisitasPorFecha(c)) {
                arch.grabarLinea(v.toString());
                modelo.eliminarVisita(v);
            }
            arch.cerrar();
            
            c.getDeposito().setContratado(false);
            modelo.eliminarContrato(c);
            JOptionPane.showMessageDialog(this, "Se dio de baja el contrato con éxito.", "Contrato dado de baja", JOptionPane.INFORMATION_MESSAGE);
            jListContratos.setListData(modelo.getListaContratos().toArray());
            jTextAreaInfoContrato.setText("");
            modeloTabla.setRowCount(0);
            jTableVisitasContrato.setModel(modeloTabla);
        }
        else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un contrato de la lista.", "Error", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonBajaContratoActionPerformed
    //Boton salir
    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed
    //Boton Mostrar datos del contrato seleccionado
    private void jButtonMostrarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarDatosActionPerformed
        Contrato c = (Contrato) jListContratos.getSelectedValue();
        if(c != null){
            jTextAreaInfoContrato.setText("Id: "+ c.getIdContrato() + "\nCliente: " + c.getCliente() + "\nEmpleado: "+ c.getEmpleado() + "\nDeposito: " + c.getDeposito() + "\nDetalle: " + c.getDetalle());
            String[] info = new String[3];
            modeloTabla.setRowCount(0);
            for (Visita v : modelo.ordenarVisitasPorFecha(c)){       
                if (v.getContrato().equals(jListContratos.getSelectedValue())){
                    info[0] = valueOf(v.getDia());
                    info[1] = valueOf(v.getMes());
                    info[2] = v.getEmpleado().toString();
                    modeloTabla.addRow(info);
                }
            }
            jTableVisitasContrato.setModel(modeloTabla);
        }
        else {
            JOptionPane.showMessageDialog(this, "No hay contratos seleccionados", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonMostrarDatosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBajaContrato;
    private javax.swing.JButton jButtonMostrarDatos;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTituloContrato;
    private javax.swing.JList jListContratos;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableVisitasContrato;
    private javax.swing.JTextArea jTextAreaInfoContrato;
    // End of variables declaration//GEN-END:variables
}
