// Juan Pedro Puig - 281088
// Nicolás Valsecchi - 192765

package interfaz;

import dominio.Sistema;
import dominio.Deposito;
import javax.swing.JOptionPane;

public class VentanaRegistroDeposito extends javax.swing.JFrame {
    //Atributo
    private Sistema modelo;
    
    //Constructor
    public VentanaRegistroDeposito(Sistema unSistema) {
        modelo = unSistema;
        initComponents();
        jRadioButtonSinEstantes.setSelected(true);
        jRadioButtonNoEsRefrigerado.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupEstantes = new javax.swing.ButtonGroup();
        buttonGroupRefrigerado = new javax.swing.ButtonGroup();
        jLabelTituloRegistroDeposito = new javax.swing.JLabel();
        jLabelIdDeposito = new javax.swing.JLabel();
        jLabelTamano = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelEstantes = new javax.swing.JLabel();
        jRadioButtonConEstantes = new javax.swing.JRadioButton();
        jRadioButtonSinEstantes = new javax.swing.JRadioButton();
        jTextFieldTamano = new javax.swing.JTextField();
        jTextFieldIdDeposito = new javax.swing.JTextField();
        jLabelRefrigerado = new javax.swing.JLabel();
        jRadioButtonEsRefrigerado = new javax.swing.JRadioButton();
        jRadioButtonNoEsRefrigerado = new javax.swing.JRadioButton();
        jButtonAgregarDeposito = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Auto-almacenamiento");

        jLabelTituloRegistroDeposito.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTituloRegistroDeposito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloRegistroDeposito.setText("Registro de depósito");
        jLabelTituloRegistroDeposito.setToolTipText("");
        jLabelTituloRegistroDeposito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelIdDeposito.setText("Número identificador:");

        jLabelTamano.setText("Tamaño:");

        jLabel3.setText("metros cuadrados.");

        jLabelEstantes.setText("Tiene estantes:");

        buttonGroupEstantes.add(jRadioButtonConEstantes);
        jRadioButtonConEstantes.setText("Sí");
        jRadioButtonConEstantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonConEstantesActionPerformed(evt);
            }
        });

        buttonGroupEstantes.add(jRadioButtonSinEstantes);
        jRadioButtonSinEstantes.setText("No");

        jLabelRefrigerado.setText("Es Refrigerado:");

        buttonGroupRefrigerado.add(jRadioButtonEsRefrigerado);
        jRadioButtonEsRefrigerado.setText("Sí");
        jRadioButtonEsRefrigerado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEsRefrigeradoActionPerformed(evt);
            }
        });

        buttonGroupRefrigerado.add(jRadioButtonNoEsRefrigerado);
        jRadioButtonNoEsRefrigerado.setText("No");

        jButtonAgregarDeposito.setText("Agregar depósito");
        jButtonAgregarDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarDepositoActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEstantes)
                            .addComponent(jLabelRefrigerado))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonConEstantes)
                            .addComponent(jRadioButtonEsRefrigerado))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonNoEsRefrigerado)
                            .addComponent(jRadioButtonSinEstantes))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelTamano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldTamano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelIdDeposito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldIdDeposito)))
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(jButtonSalir))
                            .addComponent(jButtonAgregarDeposito)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabelTituloRegistroDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(58, 58, 58)))
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelTituloRegistroDeposito)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdDeposito)
                    .addComponent(jTextFieldIdDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTamano)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldTamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEstantes)
                    .addComponent(jRadioButtonConEstantes)
                    .addComponent(jRadioButtonSinEstantes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRefrigerado)
                    .addComponent(jRadioButtonEsRefrigerado)
                    .addComponent(jRadioButtonNoEsRefrigerado))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregarDeposito)
                    .addComponent(jButtonSalir))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonConEstantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonConEstantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonConEstantesActionPerformed

    //Boton para enviar deposito
    private void jButtonAgregarDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarDepositoActionPerformed
        int idDeposito = 0;
        int tamano = 0;
        boolean ok = true;
        boolean estantes = jRadioButtonConEstantes.isSelected();
        boolean refrigerado = jRadioButtonEsRefrigerado.isSelected();
                
        try {
            idDeposito = Integer.parseInt(jTextFieldIdDeposito.getText());
            tamano = Integer.parseInt(jTextFieldTamano.getText());
            if (idDeposito < 1 || tamano < 1) {
                JOptionPane.showMessageDialog(this, "Los números ingresados deben ser positivos.", "Error", JOptionPane.WARNING_MESSAGE);
                ok = false;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Los campos solo admiten números. No pueden estar vacíos.", "Error", JOptionPane.WARNING_MESSAGE);
            ok = false;
        }
        
        if (ok) {
            Deposito d = new Deposito(idDeposito, tamano, estantes, refrigerado);
            if (!modelo.existe(modelo.getListaDepositos(), d)) {
                modelo.agregarDeposito(d);
                JOptionPane.showMessageDialog(this, "El depósito se ha ingresado con éxito.", "Depósito ingresado", JOptionPane.INFORMATION_MESSAGE);
                jTextFieldIdDeposito.setText("");
                jTextFieldTamano.setText("");
                jRadioButtonSinEstantes.setSelected(true);
                jRadioButtonNoEsRefrigerado.setSelected(true);
            } else {
                JOptionPane.showMessageDialog(this, "El depósito que está intentando ingresar ya existe.", "Depósito existente", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonAgregarDepositoActionPerformed
    private void jRadioButtonEsRefrigeradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEsRefrigeradoActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonEsRefrigeradoActionPerformed
    //Boton para salir
    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupEstantes;
    private javax.swing.ButtonGroup buttonGroupRefrigerado;
    private javax.swing.JButton jButtonAgregarDeposito;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelEstantes;
    private javax.swing.JLabel jLabelIdDeposito;
    private javax.swing.JLabel jLabelRefrigerado;
    private javax.swing.JLabel jLabelTamano;
    private javax.swing.JLabel jLabelTituloRegistroDeposito;
    private javax.swing.JRadioButton jRadioButtonConEstantes;
    private javax.swing.JRadioButton jRadioButtonEsRefrigerado;
    private javax.swing.JRadioButton jRadioButtonNoEsRefrigerado;
    private javax.swing.JRadioButton jRadioButtonSinEstantes;
    private javax.swing.JTextField jTextFieldIdDeposito;
    private javax.swing.JTextField jTextFieldTamano;
    // End of variables declaration//GEN-END:variables
}
